// @ts-check
import { test, expect } from '@playwright/test'

import { setupConvenientDiscussions } from './helpers/test-utils.js'

const TEST_TEXT = 'This is an autogenerated e2e test reply - please ignore'

/**
 * Wait for MediaWiki globals to be available.
 *
 * @param {import('@playwright/test').Page} page
 */
async function waitForMwGlobals(page) {
	await page.waitForFunction(() => window.mw && window.$ && window.OO, { timeout: 10_000 })
}

/**
 * Inject the CD dev script and wait for CD to be fully ready.
 *
 * @param {import('@playwright/test').Page} page
 */
async function injectAndWaitForCd(page) {
	await page.addScriptTag({
		type: 'module',
		url: 'http://localhost:9000/src/loader/startup.js',
	})
	await page.waitForFunction(
		() =>
			window.convenientDiscussions?.comments !== undefined &&
			window.convenientDiscussions.comments.length > 0 &&
			window.convenientDiscussions.settings,
		{ timeout: 20_000 },
	)
	// Extra wait for comment forms session restore to run.
	await page.waitForTimeout(2000)
}

test.describe('Comment form restoration after page reload', () => {
	test('should restore a reply form to its place (inside .cd-replyButtonWrapper) after F5 reload', async ({
		page,
	}) => {
		// 1. Load the page and CD for the first time.
		await setupConvenientDiscussions(
			page,
			'https://test.wikipedia.org/wiki/User_talk:JWBTH/CD_test_page',
		)

		// 2. Click the "Reply in section" button of the first section to open a reply form.
		//    The first .cd-replyButtonWrapper has an OOUI button inside it.
		const firstReplyWrapper = page.locator('.cd-replyButtonWrapper').first()
		const replyButton = firstReplyWrapper.locator('.oo-ui-buttonElement-button').first()
		await replyButton.click()

		// Wait for the form to appear inside the wrapper (class is added dynamically).
		await expect(firstReplyWrapper).toHaveClass(/cd-replyButtonWrapper-hasCommentForm/, {
			timeout: 5000,
		})
		console.log('✅ Reply form is open inside .cd-replyButtonWrapper')

		// 3. Type some text into the comment form's textarea.
		const commentTextarea = firstReplyWrapper.locator('textarea.oo-ui-inputWidget-input').first()
		await commentTextarea.click()
		await page.keyboard.type(TEST_TEXT)

		// Verify the text is stored in the CD commentForm object.
		const typedValue = await page.evaluate(() => {
			const cf = window.convenientDiscussions.commentForms?.[0]

			return cf?.commentInput?.getValue()
		})
		expect(typedValue, 'Text should be in the form before reload').toBe(TEST_TEXT)
		console.log(`✅ Typed "${TEST_TEXT}" into the reply form`)

		// 4. Reload the page (simulating F5). The beforeunload handler in CD saves the session to
		//    localStorage before the page unloads.
		await page.reload()
		console.log('🔄 Page reloaded (simulating F5)')

		// 5. Wait for MediaWiki globals to be available again, then re-inject CD.
		await page.waitForLoadState('networkidle')
		await waitForMwGlobals(page)
		console.log('⚙️ MediaWiki globals available after reload')

		// 6. Re-inject CD and wait for it to load and restore session.
		await injectAndWaitForCd(page)
		console.log('🎯 CD re-initialized after reload')

		// 7. Assert: the rescue dialog must NOT be visible.
		//    If the form was properly restored, no rescue dialog should appear.
		const rescueDialog = page.locator('.oo-ui-messageDialog')
		await expect(
			rescueDialog,
			'The rescue dialog should NOT appear when the form is properly restored',
		).not.toBeVisible()
		console.log('✅ Rescue dialog is not shown')

		// 8. Assert: a .cd-replyButtonWrapper must contain the restored comment form.
		const restoredWrapper = page.locator('.cd-replyButtonWrapper-hasCommentForm')
		await expect(
			restoredWrapper,
			'A .cd-replyButtonWrapper should contain the restored form',
		).toBeVisible({ timeout: 5000 })
		console.log('✅ Restored form is inside .cd-replyButtonWrapper')

		// 9. Assert: the text in the restored form matches what was typed before reload.
		const restoredText = await page.evaluate(() => {
			const cf = window.convenientDiscussions.commentForms?.[0]

			return cf?.commentInput?.getValue()
		})
		expect(restoredText, 'The restored form should contain the original typed text').toBe(TEST_TEXT)
		console.log(`✅ Restored form contains the correct text: "${restoredText}"`)
	})
})
