// @ts-check
import { test, expect } from '@playwright/test'

import { setupConvenientDiscussions, getSectionButtonContainer } from './helpers/test-utils.js'

const TEST_TEXT = 'This is an autogenerated e2e test reply - please ignore'

/**
 * Wait for MediaWiki globals to be available.
 *
 * @param {import('@playwright/test').Page} page
 */
async function waitForMwGlobals(page) {
	await page.waitForFunction(() => window.mw && window.$ && window.OO, { timeout: 10_000 })
}

/**
 * Inject the CD dev script and wait for CD to be fully ready.
 *
 * @param {import('@playwright/test').Page} page
 */
async function injectAndWaitForCd(page) {
	await page.addScriptTag({
		type: 'module',
		url: 'http://localhost:9000/src/loader/startup.js',
	})
	await page.waitForFunction(
		() =>
			window.convenientDiscussions?.comments !== undefined &&
			window.convenientDiscussions.comments.length > 0 &&
			window.convenientDiscussions.settings,
		{ timeout: 20_000 },
	)
	// Extra wait for comment forms session restore to run.
	await page.waitForTimeout(2000)
}

test.describe('Comment form rescue when section is missing after reload', () => {
	test('should show a rescue dialog when the section is no longer present after reload', async ({
		page,
	}) => {
		// 1. Load the page and CD for the first time.
		await setupConvenientDiscussions(
			page,
			'https://test.wikipedia.org/wiki/User_talk:JWBTH/CD_test_page',
		)

		// 2. Click the "Reply" button of "Section 1" to open a reply form.
		const sectionButtonContainer = getSectionButtonContainer(page, 'Section 1')
		const sectionReplyWrapper = sectionButtonContainer.locator('.cd-replyButtonWrapper')
		const replyButton = sectionReplyWrapper.locator('.oo-ui-buttonElement-button').first()
		await replyButton.click()

		// Wait for the form to appear inside the wrapper (class is added dynamically).
		await expect(sectionReplyWrapper).toHaveClass(/cd-replyButtonWrapper-hasCommentForm/, {
			timeout: 5000,
		})
		console.log('✅ Reply form is open inside the section button wrapper')

		// 3. Type some text into the comment form's textarea.
		const commentTextarea = sectionReplyWrapper.locator('textarea.oo-ui-inputWidget-input').first()
		await commentTextarea.click()
		await page.keyboard.type(TEST_TEXT)

		// Verify the text is stored in the CD commentForm object.
		const typedValue = await page.evaluate(() => {
			const cf = window.convenientDiscussions.commentForms?.[0]

			return cf?.commentInput?.getValue()
		})
		expect(typedValue, 'Text should be in the form before reload').toBe(TEST_TEXT)
		console.log(`✅ Typed "${TEST_TEXT}" into the reply form`)

		// 4. Reload the page (simulating F5). The beforeunload handler in CD saves the session to
		//    localStorage before the page unloads.
		await page.reload()
		console.log('🔄 Page reloaded (simulating F5)')

		// 5. Wait for MediaWiki globals to be available again.
		await page.waitForLoadState('networkidle')
		await waitForMwGlobals(page)
		console.log('⚙️ MediaWiki globals available after reload')

		// 6. Delete the #Section_1 element to simulate that the section was deleted.
		//    This causes CD to fail to find the target section when restoring the form.
		await page.evaluate(() => {
			document.querySelector('#Section_1')?.remove()
		})
		console.log('🗑️ Removed #Section_1 to simulate a deleted section')

		// 7. Re-inject CD and wait for it to load and attempt session restore.
		await injectAndWaitForCd(page)
		console.log('🎯 CD re-initialized after reload')

		// 8. Assert: the rescue dialog MUST be visible because the section is gone.
		const rescueDialog = page.locator('.oo-ui-messageDialog')
		await expect(
			rescueDialog,
			'The rescue dialog should appear when the target section is missing',
		).toBeVisible({ timeout: 5000 })
		console.log('✅ Rescue dialog is shown as expected')

		// 9. Assert: no .cd-replyButtonWrapper-hasCommentForm should exist,
		//    since the form could not be restored to its original location.
		const restoredWrapper = page.locator('.cd-replyButtonWrapper-hasCommentForm')
		await expect(
			restoredWrapper,
			'No .cd-replyButtonWrapper should contain a restored form',
		).not.toBeVisible()
		console.log('✅ Form was NOT restored to its original location (rescue dialog shown instead)')
	})
})
