export default {
	'messages': {
		'sun': '日',
		'mon': '月',
		'tue': '火',
		'wed': '水',
		'thu': '木',
		'fri': '金',
		'sat': '土',
		'sunday': '日曜日',
		'monday': '月曜日',
		'tuesday': '火曜日',
		'wednesday': '水曜日',
		'thursday': '木曜日',
		'friday': '金曜日',
		'saturday': '土曜日',
		'jan': '1月',
		'feb': '2月',
		'mar': '3月',
		'apr': '4月',
		'may': '5月',
		'jun': '6月',
		'jul': '7月',
		'aug': '8月',
		'sep': '9月',
		'oct': '10月',
		'nov': '11月',
		'dec': '12月',
		'january': '1月',
		'february': '2月',
		'march': '3月',
		'april': '4月',
		'may_long': '5月',
		'june': '6月',
		'july': '7月',
		'august': '8月',
		'september': '9月',
		'october': '10月',
		'november': '11月',
		'december': '12月',
		'january-gen': '1月',
		'february-gen': '2月',
		'march-gen': '3月',
		'april-gen': '4月',
		'may-gen': '5月',
		'june-gen': '6月',
		'july-gen': '7月',
		'august-gen': '8月',
		'september-gen': '9月',
		'october-gen': '10月',
		'november-gen': '11月',
		'december-gen': '12月',
		'parentheses': '($1)',
		'parentheses-start': '(',
		'parentheses-end': ')',
		'word-separator': ' ',
		'comma-separator': '、',
		'colon-separator': ': ',
		'nextdiff': '新しい編集 →',
		'timezone-utc': 'UTC',
		'pagetitle': '$1 - {{SITENAME}}',
		'discussiontools-topicsubscription-button-subscribe': '更新を通知',
		'discussiontools-topicsubscription-button-subscribe-tooltip': 'この節に新しいコメントが投稿されたら通知します。',
		'discussiontools-topicsubscription-button-unsubscribe': '通知を解除',
		'discussiontools-topicsubscription-button-unsubscribe-tooltip': '通知を受け取らないようにします。',
		'discussiontools-topicsubscription-notify-subscribed-title': '通知を有効にしました',
		'discussiontools-topicsubscription-notify-subscribed-body': 'このトピックに新しいコメントが投稿されたら通知を受け取ります。',
		'discussiontools-topicsubscription-notify-unsubscribed-title': '通知を無効にしました',
		'discussiontools-topicsubscription-notify-unsubscribed-body': 'このトピックに新しいコメントが投稿されても通知は届かなくなります。',
		'discussiontools-newtopicssubscription-button-subscribe-label': '購読',
		'discussiontools-newtopicssubscription-button-subscribe-tooltip': 'このページに新しい話題が追加されたとき、通知を受け取るようにします。',
		'discussiontools-newtopicssubscription-button-unsubscribe-label': '購読解除',
		'discussiontools-newtopicssubscription-button-unsubscribe-tooltip': 'このページに新しい話題が追加されても通知を受け取らないようにします。',
		'discussiontools-newtopicssubscription-notify-subscribed-title': '{{GENDER:|}}通知を有効にしました',
		'discussiontools-newtopicssubscription-notify-subscribed-body': 'このページに新しい話題が追加されると通知が届きます。',
		'discussiontools-newtopicssubscription-notify-unsubscribed-title': '通知を停止しました',
		'discussiontools-newtopicssubscription-notify-unsubscribed-body': '新しい話題が追加されても通知を受け取らないようにしました。',
		'visualeditor-educationpopup-dismiss': 'わかりました'
	},
	'specialPageAliases': {
		'Contributions': '投稿記録',
		'Diff': '差分',
		'PermanentLink': '固定リンク'
	},
	'substAliases': [
		'展開:',
		'展開：'
	],
	'thumbAliases': [
		'サムネイル',
	],
	'timezone': 'UTC',
	'useGlobalPreferences': true,
	'unsignedTemplates': [
		'Unsigned',
		'無署名',
		'Unsig',
		'Unsigned2',
		'署名補完',
		'Unsigned/old',
		'Unsigned-IPuser',
		'Unsigip',
		'署名補完/IP',
		'Unsigned-IPuser2',
		'Unsignedip2'
	],
	'paragraphTemplates': [
		'pb',
		'Paragraph break'
	],
	'outdentTemplates': [
		'outdent',
		'Od',
		'インデント戻し'
	],
	'clearTemplates': [
		'Clear',
		'Clr',
		'-',
		'Br',
		'Clear both'
	],
	'closedDiscussionTemplates': [
		[
			'古い話題のはじめ',
			'Archive top',
			'Atop',
			'Vfd top'
		],
		[
			'Archive bottom',
			'Abtm',
			'Abot',
			'Vfd bottom'
		]
	],
	'signatureEndingRegexp': /（会話）/,
	'tagName': 'convenient-discussions',
};
