/**
 * Module loaded on pages where we add comment links to history entries (sometimes more).
 *
 * @module addCommentLinks
 */

import Comment from './Comment'
import PrototypeRegistry from './PrototypeRegistry'
import commentManager from './commentManager'
import { initGlobals, initTimestampTools } from './init'
import cd from './loader/cd'
import pageRegistry from './pageRegistry'
import {
	definedAndNotNull,
	generatePageNamePattern,
	isUndo,
	removeDirMarks,
	spacesToUnderlines,
} from './shared/utils-general'
import { parseTimestamp } from './shared/utils-timestamp'

/** @type {string | undefined} */
let moveFromStringStart
/** @type {string | undefined} */
let moveToStringStart
/** @type {string} */
let goToCommentToYou
/** @type {RegExp} */
let currentUserRegexp

/**
 * @type {PrototypeRegistry<{
 *   wrapperRegular: HTMLElement
 *   wrapperRelevant: HTMLElement
 * }>}
 */
const prototypes = new PrototypeRegistry()

/**
 * _For internal use._ The entry function for the comment links adding mechanism.
 */
export default async function addCommentLinks() {
	// This could have been executed from app() already.
	initGlobals()

	try {
		await bootstrap()
	} catch (error) {
		cd.debug.logWarn(error)

		return
	}

	if (cd.loader.isPageOfType('diff')) {
		mw.hook('convenientDiscussions.pageReady').add(() => {
			processDiff()
		})
	} else {
		// Hook on wikipage.content to make the code work with the watchlist auto-update feature.
		mw.hook('wikipage.content').add(processRevisionListPage)
	}

	// Diffs generated by scripts, like Serhio Magpie's Instant Diffs.
	mw.hook('wikipage.diff').add(processDiff)
}

/**
 * Set variables needed for many routines.
 *
 * @private
 */
async function bootstrap() {
	try {
		// We need strings for parentheses (is that all?..)
		await cd.loader.getSiteDataPromise()
	} catch (error) {
		throw new Error(`Couldn't load the data required for the script.`, { cause: error })
	}

	// We need timestamp tools to be able to parse timestamps.
	initTimestampTools()

	mw.loader.addStyleTag(`:root {
		--cd-parentheses-start: '${cd.mws('parentheses-start')}';
		--cd-parentheses-end: '${cd.mws('parentheses-end')}';
	}`)
	;[moveFromStringStart] = cd.s('es-move-from').match(/^[^[$]+/) || []
	;[moveToStringStart] = cd.s('es-move-to').match(/^[^[$]+/) || []

	goToCommentToYou = cd.s('lp-comment-tooltip') + ' '
	goToCommentToYou += cd.mws('parentheses', cd.s('lp-comment-toyou'))

	// eslint-disable-next-line no-one-time-vars/no-one-time-vars
	const $aRegularPrototype = $('<a>')
		.text(cd.s('lp-comment'))
		.attr('title', cd.s('lp-comment-tooltip'))
	// eslint-disable-next-line no-one-time-vars/no-one-time-vars
	const $spanRegularPrototype = $('<span>')
		.addClass('cd-commentLink-innerWrapper')
		.append($aRegularPrototype)
	const $wrapperRegularPrototype = $('<span>')
		.addClass('cd-commentLink')
		.append($spanRegularPrototype)
		.prepend(' ')
	prototypes.add('wrapperRegular', $wrapperRegularPrototype[0])
	prototypes.add(
		'wrapperRelevant',
		$wrapperRegularPrototype.clone().addClass('cd-commentLink-relevant')[0],
	)

	const currentUserNamePattern = generatePageNamePattern(cd.g.userName)
	currentUserRegexp = new RegExp(
		`(?:^|[^${cd.g.letterPattern}])${currentUserNamePattern}(?![${cd.g.letterPattern}])`,
	)
}

/**
 * Add comment links to the revisions listed on the page that is a revision list page (not a diff
 * page, for instance).
 *
 * @param {JQuery} $content
 * @private
 */
function processRevisionListPage($content) {
	// Occurs in the watchlist when mediawiki.rcfilters.filters.ui module for some reason fires
	// wikipage.content for the second time with an element that is not in the DOM,
	// fieldset#mw-watchlist-options (in the mw.rcfilters.ui.FormWrapperWidget#onChangesModelUpdate
	// function).
	if (!$content.parent().length) return

	if (cd.loader.isPageOfType('watchlist')) {
		processWatchlist($content)
	} else if (cd.loader.isPageOfType('contributions')) {
		processContributions($content)
	} else if (cd.loader.isPageOfType('history')) {
		processHistory($content)
	}

	mw.hook('convenientDiscussions.commentLinksAdded').fire($content, cd)
}

/**
 * Add comment links to a watchlist or a recent changes page.
 *
 * @param {JQuery} $content
 * @private
 */
function processWatchlist($content) {
	// There are 2 ^ 3 = 8 (!) different watchlist modes:
	// * expanded and not (Special:Preferences#mw-prefsection-watchlist "Expand watchlist to show all
	//   changes, not just the most recent")
	// * with item grouping and without (Special:Preferences#mw-prefsection-rc "Group changes by page
	//   in recent changes and watchlist")
	// * with enhanced fitlers and without (Special:Preferences#mw-prefsection-watchlist "Use
	//   non-JavaScript interface")
	// eslint-disable-next-line no-one-time-vars/no-one-time-vars
	const lines = /** @type {NodeListOf<HTMLElement>} */ (
		$content[0].querySelectorAll('.mw-changeslist-line[data-mw-revid]')
	)
	lines.forEach((lineOrBareTr) => {
		const line = lineOrBareTr.className
			? lineOrBareTr
			: /** @type {HTMLElement} */ (
					/** @type {HTMLElement} */ (lineOrBareTr.parentElement).parentElement
				)
		const nsMatch = line.className.match(/mw-changeslist-ns(\d+)/)
		const nsNumber = nsMatch && Number(nsMatch[1])
		if (nsNumber === null) return

		const linkElement = /** @type {HTMLAnchorElement | undefined} */ (
			(line.tagName === 'TR'
				? /** @type {HTMLElement} */ (line.parentElement)
				: line
			).querySelector('.mw-changeslist-title')
		)
		if (
			!linkElement ||
			isWikidataItem(linkElement) ||
			!cd.loader.isProbablyTalkPage(linkElement.textContent, nsNumber) ||
			line.querySelector('.minoredit')
		)
			return

		let summary = line.querySelector('.comment')?.textContent
		summary &&= removeDirMarks(summary)
		if (summary && (isCommentEdit(summary) || isUndo(summary) || isMoved(summary))) return

		const bytesAddedElement = line.querySelector('.mw-plusminus-pos')
		if (!bytesAddedElement) return

		if (bytesAddedElement.tagName !== 'STRONG') {
			const bytesAddedMatch = bytesAddedElement.textContent.match(/\d+/)
			const bytesAdded = bytesAddedMatch && Number(bytesAddedMatch[0])
			if (!bytesAdded || bytesAdded < cd.config.bytesToDeemComment) return
		}

		const timestamp = line.dataset.mwTs?.slice(0, 12)
		if (!timestamp) return

		const author = extractAuthor(line)
		if (!author) return

		const id = timestamp + '_' + spacesToUnderlines(author)

		const link = linkElement.href
		if (!link) return

		let wrapper
		if (summary && currentUserRegexp.test(` ${summary} `)) {
			wrapper = prototypes.get('wrapperRelevant')
			setWrapperLinkAttr(wrapper, 'title', goToCommentToYou)
		} else {
			wrapper = prototypes.get('wrapperRegular')
		}

		setWrapperLinkAttr(wrapper, 'href', `${link}#${id}`)

		const destination = line.querySelector('.comment') || line.querySelector('.mw-usertoollinks')
		if (!destination) return

		const destinationParent = /** @type {HTMLElement} */ (destination.parentElement)
		destinationParent.insertBefore(wrapper, destination.nextSibling)
	})
}

/**
 * Add comment links to a contributions page.
 *
 * @param {JQuery} $content
 * @private
 */
function processContributions($content) {
	// We need timestamp tools to be able to parse timestamps
	if (cd.g.timestampTools.user.timezone === undefined) return
	;[
		...$content[0].querySelectorAll('.mw-contributions-list > li:not(.mw-tag-mw-new-redirect)'),
	].forEach((line) => {
		const linkElement = /** @type {HTMLAnchorElement | null} */ (
			line.querySelector('.mw-contributions-title')
		)
		if (!linkElement || isWikidataItem(linkElement)) return

		const page = pageRegistry.get(linkElement.textContent, true)
		if (!page?.isProbablyTalkPage()) return

		const link = linkElement.href
		if (!link) return

		if (line.querySelector('.minoredit')) return

		let summary = line.querySelector('.comment')?.textContent
		summary &&= removeDirMarks(summary)
		if (summary && (isCommentEdit(summary) || isUndo(summary) || isMoved(summary))) return

		const bytesAddedElement = line.querySelector('.mw-plusminus-pos')
		if (!bytesAddedElement) return

		if (bytesAddedElement.tagName !== 'STRONG') {
			const bytesAddedMatch = bytesAddedElement.textContent.match(/\d+/)
			const bytesAdded = bytesAddedMatch && Number(bytesAddedMatch[0])
			if (!bytesAdded || bytesAdded < cd.config.bytesToDeemComment) return
		}

		const dateElement = line.querySelector('.mw-changeslist-date')
		if (!dateElement) return

		const { date } = parseTimestamp(dateElement.textContent, true) || {}
		if (!date) return

		const id = Comment.generateId(date, mw.config.get('wgRelevantUserName') || undefined)
		if (!id) return

		let wrapper
		if (summary && currentUserRegexp.test(` ${summary} `)) {
			wrapper = prototypes.get('wrapperRelevant')
			setWrapperLinkAttr(wrapper, 'title', goToCommentToYou)
		} else {
			wrapper = prototypes.get('wrapperRegular')
		}
		setWrapperLinkAttr(wrapper, 'href', `${link}#${id}`)

		let destination = line.querySelector('.comment')
		if (!destination) {
			destination = linkElement
			if (destination.nextSibling) {
				destination.nextSibling.textContent = destination.nextSibling.textContent.replace(/^\s/, '')
			}
		}
		const destinationParent = /** @type {HTMLElement} */ (destination.parentElement)
		destinationParent.insertBefore(wrapper, destination.nextSibling)
	})
}

/**
 * Add comment links to a history page.
 *
 * @param {JQuery} $content
 * @private
 */
function processHistory($content) {
	// We need timestamp tools to be able to parse timestamps
	if (cd.g.timestampTools.user.timezone === undefined) return

	const link = cd.page.getUrl()
	;[
		...$content[0].querySelectorAll(
			'#pagehistory > li, #pagehistory > .mw-contributions-list > li:not(.mw-tag-mw-new-redirect)',
		),
	].forEach((line) => {
		if (line.querySelector('.minoredit')) return

		let summary = line.querySelector('.comment')?.textContent
		summary &&= removeDirMarks(summary)
		if (summary && (isCommentEdit(summary) || isUndo(summary) || isMoved(summary))) return

		const bytesAddedElement = line.querySelector('.mw-plusminus-pos')
		if (!bytesAddedElement) return

		if (bytesAddedElement.tagName !== 'STRONG') {
			const bytesAddedMatch = bytesAddedElement.textContent.match(/\d+/)
			const bytesAdded = bytesAddedMatch && Number(bytesAddedMatch[0])
			if (!bytesAdded || bytesAdded < cd.config.bytesToDeemComment) return
		}

		const dateElement = line.querySelector('.mw-changeslist-date')
		if (!dateElement) return

		const { date } = parseTimestamp(dateElement.textContent, true) || {}
		if (!date) return

		const author = extractAuthor(line)
		if (!author) return

		const id = Comment.generateId(date, author)

		let wrapper
		if (summary && currentUserRegexp.test(` ${summary} `)) {
			wrapper = prototypes.get('wrapperRelevant')
			setWrapperLinkAttr(wrapper, 'title', goToCommentToYou)
		} else {
			wrapper = prototypes.get('wrapperRegular')
		}
		setWrapperLinkAttr(wrapper, 'href', `${link}#${id}`)

		const destination =
			line.querySelector('.comment') ||
			[...line.querySelectorAll('.mw-changeslist-separator')].at(-1)
		if (!destination) return

		const destinationParent = /** @type {HTMLElement} */ (destination.parentElement)
		destinationParent.insertBefore(wrapper, destination.nextSibling)
	})
}

/**
 * Add a comment link to a diff view.
 *
 * @param {JQuery} [$diff]
 * @fires commentLinksAdded
 * @private
 */
function processDiff($diff) {
	// Filter out cases when wikipage.diff was fired for the native MediaWiki's diff at the top of the
	// page that is a diff page (unless only a diff, and no content, is displayed - if
	// mw.user.options.get('diffonly') or the `diffonly` URL parameter is true). If CD is booted on
	// the talk page (`.cd-parsed` is found), we parse that diff on convenientDiscussions.pageReady
	// hook instead.

	// eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
	if (
		($diff?.parent().is(cd.loader.$content) && $('.cd-parsed').length) ||
		cd.g.timestampTools.user.timezone === undefined
	)
		return

	const $root = $diff || cd.loader.$content
	const root = $root[0]
	;[root.querySelector('.diff-otitle'), root.querySelector('.diff-ntitle')]
		.filter(definedAndNotNull)
		.forEach((area) => {
			if (area.querySelector('.minoredit')) return

			area.querySelector('.cd-commentLink')?.remove()

			let summary = area.querySelector('.comment')?.textContent
			summary &&= removeDirMarks(summary)

			// In diffs, archivation can't be captured by looking at bytes added.
			if (
				summary &&
				(isCommentEdit(summary) || isUndo(summary) || isMoved(summary) || isArchiving(summary))
			) {
				return
			}

			const dateElement = /** @type {HTMLAnchorElement | null} */ (
				area.querySelector('#mw-diff-otitle1 a, #mw-diff-ntitle1 a')
			)
			if (!dateElement) return

			const { date } = parseTimestamp(dateElement.textContent, true) || {}
			if (!date) return

			const author = extractAuthor(area)
			if (!author) return

			const id = Comment.generateId(date, author)

			/** @type {import('./Comment').default | undefined} */
			let comment
			let page
			if ($diff) {
				const title = new URL(dateElement.href).searchParams.get('title')
				if (!title) return

				page = pageRegistry.get(title, true)
				if (!page) return
			} else {
				comment = commentManager.getById(id, true)
			}
			if (comment || page?.isProbablyTalkPage()) {
				let wrapper
				if (summary && currentUserRegexp.test(` ${summary} `)) {
					wrapper = prototypes.get('wrapperRelevant')
					setWrapperLinkAttr(wrapper, 'title', goToCommentToYou)
				} else {
					wrapper = prototypes.get('wrapperRegular')
				}

				const linkElement = /** @type {HTMLAnchorElement} */ (
					/** @type {HTMLElement} */ (wrapper.lastChild).lastChild
				)
				if (page) {
					linkElement.href = page.getUrl() + '#' + id

					// Non-diff pages that have a diff, like with Serhio Magpie's Instant Diffs.
					if (cd.loader.isPageOfType('talk')) {
						linkElement.target = '_blank'
					}
				} else {
					linkElement.href = '#' + id
					linkElement.addEventListener('click', (event) => {
						event.preventDefault()
						const commentTyped = /** @type {NonNullable<typeof comment>} */ (comment)
						commentTyped.scrollTo({
							smooth: false,
							pushState: true,
							expandThreads: true,
						})
					})
				}

				const destination = area.querySelector('#mw-diff-otitle3, #mw-diff-ntitle3')
				if (!destination) return

				destination.append(wrapper)
			}
		})

	/**
	 * Comments links have been added to the revisions listed on the page.
	 *
	 * @event commentLinksAdded
	 * @param {JQuery} $root Root element of content to which the comment links were added.
	 * @param {object} cd {@link convenientDiscussions} object.
	 * @global
	 */
	mw.hook('convenientDiscussions.commentLinksAdded').fire($root, cd)
}

/**
 * Check by an edit summary if an edit is probably an edit of a comment.
 *
 * @param {string} summary
 * @returns {boolean}
 */
function isCommentEdit(summary) {
	return Boolean(
		summary &&
		(summary.includes(`${cd.s('es-edit')} ${cd.s('es-reply-genitive')}`) ||
			summary.includes(`${cd.s('es-edit')} ${cd.s('es-addition-genitive')}`)),
	)
}

/**
 * Check by an edit summary if an edit is probably a move performed by our script.
 *
 * @param {string} summary
 * @returns {boolean}
 * @private
 */
function isMoved(summary) {
	return Boolean(
		(moveFromStringStart && summary.includes(': ' + moveFromStringStart)) ||
		(moveToStringStart && summary.includes(': ' + moveToStringStart)),
	)
}

/**
 * Whether the provided link element points to a Wikidata item.
 *
 * @param {Element} linkElement
 * @returns {boolean}
 * @private
 */
function isWikidataItem(linkElement) {
	return Boolean(
		cd.g.serverName === 'www.wikidata.org' &&
		linkElement.firstElementChild?.classList.contains('wb-itemlink'),
	)
}

/**
 * Extract an author given a revision line.
 *
 * @param {Element} line
 * @returns {?string}
 * @private
 */
function extractAuthor(line) {
	const authorElement = line.querySelector('.mw-userlink')
	if (!authorElement) {
		return null
	}
	let author = authorElement.textContent
	if (author === 'MediaWiki message delivery') {
		return null
	}
	if (mw.util.isIPv6Address(author)) {
		author = author.toUpperCase()
	}

	return author
}

/**
 * Given a wrapper element of any known kind, change an attribute on its link element.
 *
 * @param {HTMLElement} wrapper
 * @param {string} attr
 * @param {string} value
 */
function setWrapperLinkAttr(wrapper, attr, value) {
	// eslint-disable-next-line no-one-time-vars/no-one-time-vars
	const linkElement = /** @type {HTMLAnchorElement} */ (
		/** @type {HTMLElement} */ (wrapper.lastChild).lastChild
	)
	linkElement.setAttribute(attr, value)
}

/**
 * Check by an edit summary if an edit is probably an archiving operation.
 *
 * @param {string} summary
 * @returns {boolean}
 * @private
 */
function isArchiving(summary) {
	return summary.includes('Archiving')
}
