name: Deploy documentation

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run docs
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
            REMOTE_HOST: "tools-login.wmflabs.org"
            REMOTE_USER: ${{ secrets.TOOLFORGE_USER }}
            SSH_PRIVATE_KEY: ${{ secrets.TOOLFORGE_KEY }}
            ARGS: "-rltgoDzvO --delete"
            SOURCE: "dist/docs/"
            TARGET: "/data/project/convenient-discussions/www/static/docs"
      - name: Take file ownership to the tool
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: "tools-login.wmflabs.org"
          username: ${{ secrets.TOOLFORGE_USER }}
          key: ${{ secrets.TOOLFORGE_KEY }}
          script: become convenient-discussions bash -c 'cd www/static && take docs && chmod -R g+w docs'
